### ISSUE TITLE
老哥，我手头有一个谷歌浏览器扩展的小草自动评论扩展，不过只能新手用，但是我想改为侠客使用，您能帮忙改改吗，qq1245527569

### ISSUE THREAD

**Issue by shajia1992** [zhandouxiaojiji/robot1024#1]
老哥，我手头有一个谷歌浏览器扩展的小草自动评论扩展，不过只能新手用，但是我想改为侠客使用，您能帮忙改改吗，qq1245527569

**Comment by zhandouxiaojiji** [comment]
我没写过浏览器扩展，你有源码吗，或许我可以看看

**Comment by zhupeiyuan-2016** [comment]
> 老哥，我手头有一个谷歌浏览器扩展的小草自动评论扩展，不过只能新手用，但是我想改为侠客使用，您能帮忙改改吗，qq1245527569

大佬，可以发一个码嘛。

**Comment by zhupeiyuan-2016** [comment]
> 我没写过浏览器扩展，你有源码吗，或许我可以看看

大佬，可以发一个码嘛。

**Comment by zhandouxiaojiji** [comment]
暂时还没攒够U哦
